<?php
class CrmCrmCustomerAfwStructure
{
	public static function initInstance(&$obj)
	{
		if ($obj instanceof CrmCustomer) {
			$obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
                
			$arrDisp = [];
			$arrDisp["ar"] = ["first_name_ar", "father_name_ar", "last_name_ar", "mobile", "idn"];
			$arrDisp["en"] = ["first_name_en", "father_name_en", "last_name_en", "mobile", "idn"];

			$obj->DISPLAY_FIELD_BY_LANG = $arrDisp;
			$obj->DISPLAY_SEPARATOR = " ";
			$obj->AUTOCOMPLETE_FIELD = array("mobile", "email", "idn");
			$obj->ORDER_BY_FIELDS = "mobile, email, idn_type_id, idn";


			$obj->UNIQUE_KEY = array('mobile', 'email', 'idn_type_id', 'idn');
			$obj->editByStep = true;
			$obj->editNbSteps = 3;
			$obj->showQeditErrors = true;
			$obj->showRetrieveErrors = true;
			$obj->STATS_DEFAULT_CODE = "gs001";	
		} else {
			// CrmCustomerArTranslator::initData();
			// CrmCustomerEnTranslator::initData();
		}
	}


	public static $DB_STRUCTURE = array(


		'id' => array(
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => false,
			'TYPE' => 'PK',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => true,
			'STEP' => 1,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'mobile' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'MIN-SIZE' => 10,
			'MAXLENGTH' => 16,
			'CHAR_TEMPLATE' => 'BRACKETS,MATH-SYMBOLS,NUMERIC',
			'MANDATORY' => true,
			'FORMAT' => 'SA-MOBILE',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'idn_type_id' => array(
			'STEP' => 1,
			'SHORTNAME' => 'idntype',
			'SEARCH' => false,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 16,
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'ENUM',
			'ANSWER' => 'FUNCTION',
			'READONLY' => false,
			'EDIT-SHORT-LIST' => true,
			'ANSMODULE' => 'crm',
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'idn' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'MIN-SIZE' => 5,
			'FORMAT' => 'SA-IDN',
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'IDN-TYPE-ATTRIBUTE' => 'idn_type_id',
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'email' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'MIN-SIZE' => 7,
			'MAXLENGTH' => 64,
			'MANDATORY' => true,
			'FORMAT' => 'EMAIL',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'gender_id' => array(
			'STEP' => 1,
			'SHORTNAME' => 'gender',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'UTF8' => false,
			'TYPE' => 'ENUM',
			'ANSWER' => 'FUNCTION',
			'RELATION' => 'ManyToOne',
			'READONLY' => false,
			'ANSMODULE' => 'crm',
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'first_name_ar' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => 'ARABIC-CHARS,SPACE',
			'REQUIRED' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'MANDATORY' => true,
			'ERROR-CHECK' => true,
		),

		'father_name_ar' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => '',
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'last_name_ar' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => '',
			'REQUIRED' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'MANDATORY' => true,
			'ERROR-CHECK' => true,
		),

		'full_name' => array(
			'STEP' => 999,
			'TYPE' => 'TEXT',
			'CATEGORY' => 'FORMULA',
			'RETRIEVE' => true,
			'SHOW' => true,
			'QSEARCH' => true,
			'SEARCH' => true,
			'UTF8' => true,
			'FIELD-FORMULA' => "concat(IF(ISNULL(first_name_ar), '', first_name_ar) , ' ' , IF(ISNULL(father_name_ar), '', father_name_ar) , ' ' , IF(ISNULL(last_name_ar), '', last_name_ar))",
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'customer_type_id' => array(
			'STEP' => 1,
			'SHORTNAME' => 'type',
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'DEFAUT' => 1,
			'SIZE' => 32,
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'ENUM',
			'ANSWER' => 'FUNCTION',
			'ANSMODULE' => 'crm',
			'READONLY' => false,
			'EDIT-SHORT-LIST' => true,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'ERROR-CHECK' => true,
		),

		'first_name_en' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => 'ALPHABETIC,SPACE',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'father_name_en' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => 'ALPHABETIC,SPACE',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'last_name_en' => array(
			'STEP' => 1,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 24,
			'MIN-SIZE' => 3,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => 'ALPHABETIC,SPACE',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'full_name_en' => array(
			'STEP' => 999,
			'TYPE' => 'TEXT',
			'CATEGORY' => 'FORMULA',
			'RETRIEVE' => true,
			'SHOW' => true,
			'QSEARCH' => true,
			'SEARCH' => true,
			'UTF8' => true,
			'FIELD-FORMULA' => "concat(IF(ISNULL(first_name_en), '', first_name_en) , ' ' , IF(ISNULL(father_name_en), '', father_name_en) , ' ' , IF(ISNULL(last_name_en), '', last_name_en))",
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'customer_orgunit_id' => array(
			'STEP' => 2,
			'SHORTNAME' => 'orgunit',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'orgunit',
			'ANSMODULE' => 'hrm',
			'AUTOCOMPLETE' => true,
			'RELATION' => 'ManyToOne',
			'READONLY' => false,
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		

		'ref_num' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MIN-SIZE' => 5,
			'CHAR_TEMPLATE' => '',
			'MANDATORY' => false,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => false,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'org_name' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 64,
			'MIN-SIZE' => 5,
			'CHAR_TEMPLATE' => '',
			'MANDATORY' => false,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => false,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'phone' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'MIN-SIZE' => 3,
			'CHAR_TEMPLATE' => 'BRACKETS,MATH-SYMBOLS,NUMERIC',
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'region_id' => array(
			'STEP' => 2,
			'SHORTNAME' => 'region',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'region',
			'ANSMODULE' => 'ums',
			'DEPENDENT_OFME' => array(
				0 => 'city_id',
			),
			'RELATION' => 'ManyToOne',
			'READONLY' => false,
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'city_id' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 16,
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'city',
			'ANSMODULE' => 'ums',
			'WHERE' => "§region_id§='0' or region_id = §region_id§",
			'DEPENDENCY' => 'region_id',
			'RELATION' => 'ManyToOne',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'other_city' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 255,
			'CHAR_TEMPLATE' => '',
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'lang_id' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SHORTNAME' => 'lang',
			'SIZE' => 16,
			'UTF8' => false,
			'TYPE' => 'enum',
			'ANSWER' => 'FUNCTION',
			'DEFAUT' => 1,
			'RELATION' => 'ManyToOne',
			'READONLY' => false,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'hijri' => array(
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'DEFAUT' => 'Y',
			'TYPE' => 'YN',
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'service_satisfied' => array(
			'FGROUP' => 'status',  /* 'STEP' => 5,  */
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'QSIZE' => 3,
			'SIZE' => 32,
			'UTF8' => false,
			'TYPE' => 'YN',
			'DEFAUT' => 'N',
			'READONLY' => true,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_50',
		),

		'pb_resolved' => array(
			'FGROUP' => 'status',  /* 'STEP' => 5,  */
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'UTF8' => false,
			'QSIZE' => 3,
			'TYPE' => 'YN',
			'DEFAUT' => 'N',
			'READONLY' => true,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_50',
		),



		'last_request_date' => array(
			'FGROUP' => 'tech_data',  /* 'STEP' => 1,  */
			'SEARCH' => true,
			'QSEARCH' => true,
			'QSEARCH_OPER' => 'between',
			'QSIZE' => 6,
			'CSS' => 'width_pct_33',
			'SIZE' => 40,
			'TYPE' => 'DATE',
			'FORMAT' => 'CONVERT_NASRANI_VERY_SIMPLE',
			'RETRIEVE-VALUE' => false,
			'READONLY' => true,
			'SEARCH-BY-ONE' => true,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'READONLY' => true,
		),


		'requestList' => array(
			'STEP' => 3,
			'SHORTNAME' => 'requests',
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => true,
			'DELETE-ICON' => true,
			'BUTTONS' => true,
			'SEARCH' => true,
			'QSEARCH' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'request',
			'ANSMODULE' => 'crm',
			'ITEM' => 'customer_id',
			'WHERE' => "status_id in (1,2,201,3,301,4,5, 101, 102)",
			'ORDER_BY' => 'status_date desc, status_time desc',
			'READONLY' => true,
			'CAN-BE-SETTED' => false,
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'oldRequestList' => array(
			'STEP' => 3,
			'SHORTNAME' => 'requests',
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => true,
			'DELETE-ICON' => true,
			'BUTTONS' => true,
			'SEARCH' => true,
			'QSEARCH' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'request',
			'ANSMODULE' => 'crm',
			'ITEM' => 'customer_id',
			'WHERE' => "status_id not in (1,2,201,3,301,4,5, 101, 102)",
			'ORDER_BY' => 'status_date desc, status_time desc',
			'READONLY' => true,
			'CAN-BE-SETTED' => false,
			'SEARCH-BY-ONE' => false,
			'DISPLAY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),


		'this_month' => array(
			'TYPE' => 'INT',
			'CATEGORY' => 'FORMULA',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'previous_month' => array(
			'TYPE' => 'INT',
			'CATEGORY' => 'FORMULA',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'older_customer' => array(
			'TYPE' => 'INT',
			'CATEGORY' => 'FORMULA',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'date_start_stats' => array(
			'TYPE' => 'DATE',
			'CATEGORY' => 'FORMULA',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',  /* 'STEP' => 1, */
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'date_end_stats' => array(
			'TYPE' => 'DATE',
			'CATEGORY' => 'FORMULA',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',  /* 'STEP' => 1, */
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),


		'active' => array(
			'SHOW-ADMIN' => true,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'DEFAUT' => 'Y',
			'TYPE' => 'YN',
			'SEARCH-BY-ONE' => '',
			'DISPLAY' => '',
			'STEP' => 1,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
		),

		'created_by'         => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'TECH_FIELDS-RETRIEVE' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'auser',
			'ANSMODULE' => 'ums',
			'FGROUP' => 'tech_fields'
		),

		'created_at'            => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'TECH_FIELDS-RETRIEVE' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'GDAT',
			'FGROUP' => 'tech_fields'
		),

		'updated_by'           => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'TECH_FIELDS-RETRIEVE' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'auser',
			'ANSMODULE' => 'ums',
			'FGROUP' => 'tech_fields'
		),

		'updated_at'              => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'TECH_FIELDS-RETRIEVE' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'GDAT',
			'FGROUP' => 'tech_fields'
		),

		'validated_by'       => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'auser',
			'ANSMODULE' => 'ums',
			'FGROUP' => 'tech_fields'
		),

		'validated_at'          => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'GDAT',
			'FGROUP' => 'tech_fields'
		),

		/* 'active'                   => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 
                                                                'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),*/

		'version'                  => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'INT',
			'FGROUP' => 'tech_fields'
		),

		// 'draft'                         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 
		//                                        'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),

		'update_groups_mfk'             => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'ANSWER' => 'ugroup',
			'ANSMODULE' => 'ums',
			'TYPE' => 'MFK',
			'FGROUP' => 'tech_fields'
		),

		'delete_groups_mfk'             => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'ANSWER' => 'ugroup',
			'ANSMODULE' => 'ums',
			'TYPE' => 'MFK',
			'FGROUP' => 'tech_fields'
		),

		'display_groups_mfk'            => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'ANSWER' => 'ugroup',
			'ANSMODULE' => 'ums',
			'TYPE' => 'MFK',
			'FGROUP' => 'tech_fields'
		),

		'sci_id'                        => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'SHOW' => true,
			'RETRIEVE' => false,
			'QEDIT' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'scenario_item',
			'ANSMODULE' => 'ums',
			'FGROUP' => 'tech_fields'
		),

		'tech_notes' 	                => array(
			'STEP' => 99,
			'HIDE_IF_NEW' => true,
			'TYPE' => 'TEXT',
			'CATEGORY' => 'FORMULA',
			"SHOW-ADMIN" => true,
			'TOKEN_SEP' => "§",
			'READONLY' => true,
			"NO-ERROR-CHECK" => true,
			'FGROUP' => 'tech_fields'
		),
	);
}
