<?php
class MsgCMessageAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof CMessage) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = 'id';
            $obj->ORDER_BY_FIELDS = 'customer_id, subject';

            $obj->UNIQUE_KEY = array( 'customer_id', 'subject' );

            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
            $obj->nowrap_cols = array();
            $obj->nowrap_cols[ 'sms_sent_date' ] = true;
        } else {
            // CMessageArTranslator::initData();
            // CMessageEnTranslator::initData();
        }
    }
    public static $DB_STRUCTURE = [
        "id" => [
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "TYPE" => "PK",
        ],
        "sender_config_id" => [
            "SHORTNAME" => "config",
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "sender_config",
            "ANSMODULE" => "msg",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "customer_id" => [
            "SHORTNAME" => "customer",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "customer",
            "ANSMODULE" => "msg",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "subject" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ARABIC-CHARS,SPACE",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "body" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => "AREA",
            "MANDATORY" => true,
            "UTF8" => true,
            "ROWS" => 8,
            "FORMAT" => "PRE",
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "sms_tobe_sent" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "YN",
            "CHECKBOX" => true,
            "READONLY" => false,
        ],
        "sms_sent" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "YN",
            "CHECKBOX" => true,
            "READONLY" => false,
            "DEFAULT" => "N",
        ],
        "mobile" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 20,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
            "FORMAT" => "SA-MOBILE",
            "MANDATORY" => true,
        ],
        "sms_sent_date" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 10,
            "UTF8" => false,
            "TYPE" => "DATE",
            "FORMAT" => "HIJRI_UNIT",
            "READONLY" => false,
        ],
        "email_tobe_sent" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "YN",
            "CHECKBOX" => true,
            "READONLY" => false,
        ],
        "email_sent" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "YN",
            "CHECKBOX" => true,
            "READONLY" => false,
            "DEFAULT" => "N",
        ],
        "email" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 64,
            "FORMAT" => "EMAIL",
            "UTF8" => false,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "email_sent_date" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 10,
            "UTF8" => false,
            "TYPE" => "DATE",
            "FORMAT" => "HIJRI_UNIT",
            "READONLY" => false,
        ],
        "creation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "creation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "update_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "update_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "validation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "validation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "active" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "DEFAULT" => "Y",
            "TYPE" => "YN",
        ],
        "version" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "INT",
        ],
        "update_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "delete_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "display_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "sci_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "scenario_item",
            "ANSMODULE" => "pag",
        ],
        "tech_notes" => [
            "TYPE" => "TEXT",
            "CATEGORY" => "FORMULA",
            "SHOW-ADMIN" => true,
            "STEP" => "all",
            "TOKEN_SEP" => "§",
            "READONLY" => true,
            "NO-ERROR-CHECK" => true,
        ],
    ];
}
