<?php
class MsgCSystemAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof CSystem) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = "id";
            $obj->ORDER_BY_FIELDS = "code";
                
            
            $obj->UNIQUE_KEY = array('code');
            $obj->editByStep = true;
            $obj->editNbSteps = 2;
            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
        } else {
            // CSystemArTranslator::initData();
            // CSystemEnTranslator::initData();
        }
    }

    public static $DB_STRUCTURE = [
        "id" => [
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "TYPE" => "PK",
        ],
        "code" => [
            "STEP" => 1,
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 16,
            "MIN-SIZE" => 3,
            "CHAR_TEMPLATE" => "ALPHABETIC,NUMERIC,UNDERSCORE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "name" => [
            "STEP" => 1,
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ARABIC-CHARS,SPACE",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "description" => [
            "STEP" => 1,
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => "AREA",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field_count" => [
            "STEP" => 1,
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "INT",
            "READONLY" => false,
            "DEFAULT" => 1,
        ],
        "field1_type" => [
            "STEP" => 1,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field1_name" => [
            "STEP" => 1,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field2_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field2_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field3_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field3_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field4_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field4_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field5_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field5_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field6_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field6_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field7_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field7_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field8_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field8_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field9_type" => [
            "STEP" => 2,
            "SHORTNAME" => "type",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 40,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "afield_type",
            "ANSMODULE" => "pag",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field9_name" => [
            "STEP" => 2,
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "creation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "creation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "update_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "update_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "validation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "validation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "active" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "DEFAULT" => "Y",
            "TYPE" => "YN",
        ],
        "version" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "INT",
        ],
        "update_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "delete_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "display_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "sci_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "scenario_item",
            "ANSMODULE" => "pag",
        ],
        "tech_notes" => [
            "TYPE" => "TEXT",
            "CATEGORY" => "FORMULA",
            "SHOW-ADMIN" => true,
            "STEP" => "all",
            "TOKEN_SEP" => "§",
            "READONLY" => true,
            "NO-ERROR-CHECK" => true,
        ],
    ];
}
