<?php
class MsgCustomerAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof Customer) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = "id";
            $obj->ORDER_BY_FIELDS = "mobile, idn";
                
            
            $obj->UNIQUE_KEY = array('mobile','idn');
            
            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
        } else {
            // CustomerArTranslator::initData();
            // CustomerEnTranslator::initData();
        }
    }
    public static $DB_STRUCTURE = [
        "id" => [
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "TYPE" => "PK",
        ],
        "mobile" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 10,
            "FORMAT" => "SA-MOBILE",
            "UTF8" => false,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "idn" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 20,
            "UTF8" => false,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "gender_id" => [
            "STEP" => 1,
            "SHORTNAME" => "gender",
            "SEARCH" => true,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 32,
            "MAXLENGTH" => 32,
            "MANDATORY" => true,
            "UTF8" => false,
            "TYPE" => "ENUM",
            "ANSWER" => "FUNCTION",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "first_name" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "MIN-SIZE" => 2,
            "CHAR_TEMPLATE" => "ARABIC-CHARS,SPACE",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "last_name" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "MIN-SIZE" => 2,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "email" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "FORMAT" => "EMAIL",
            "UTF8" => false,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "customer_type" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 128,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "c_system_mfk" => [
            "SHORTNAME" => "systems",
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => false,
            "TYPE" => "MFK",
            "ANSWER" => "c_system",
            "ANSMODULE" => "msg",
            "READONLY" => false,
        ],
        "customer_code" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "MIN-SIZE" => 3,
            "CHAR_TEMPLATE" => "ALPHABETIC,NUMERIC,UNDERSCORE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "unit_type" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => false,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "unit_code" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => false,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "SIZE" => 16,
            "MIN-SIZE" => 1,
            "UTF8" => false,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "unit_name" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => false,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "SIZE" => 48,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ALPHABETIC,SPACE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "customerFieldList" => [
            "SHORTNAME" => "customerFields",
            "SHOW" => true,
            "FORMAT" => "retrieve",
            "ICONS" => true,
            "DELETE-ICON" => true,
            "BUTTONS" => true,
            "SEARCH" => false,
            "QSEARCH" => false,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "MANDATORY" => false,
            "UTF8" => false,
            "TYPE" => "FK",
            "CATEGORY" => "ITEMS",
            "ANSWER" => "customer_field",
            "ANSMODULE" => "msg",
            "ITEM" => "customer_id",
            "READONLY" => false,
            "CAN-BE-SETTED" => true,
        ],
        "cMessageList" => [
            "TYPE" => "FK",
            "ANSWER" => "c_message",
            "ANSMODULE" => "msg",
            "CATEGORY" => "ITEMS",
            "ITEM" => "customer_id",
            "WHERE" => "",
            "SHOW" => true,
            "FORMAT" => "retrieve",
            "EDIT" => true,
            "READONLY" => true,
            "ICONS" => true,
            "DELETE-ICON" => true,
            "BUTTONS" => true,
            "NO-LABEL" => false,
        ],
        "creation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "creation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "update_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "update_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "validation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "validation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "active" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "DEFAULT" => "Y",
            "TYPE" => "YN",
        ],
        "version" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "INT",
        ],
        "update_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "delete_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "display_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "sci_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "scenario_item",
            "ANSMODULE" => "pag",
        ],
        "tech_notes" => [
            "TYPE" => "TEXT",
            "CATEGORY" => "FORMULA",
            "SHOW-ADMIN" => true,
            "STEP" => "all",
            "TOKEN_SEP" => "§",
            "READONLY" => true,
            "NO-ERROR-CHECK" => true,
        ],
    ];
}
