<?php
class MsgCustomerFieldAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof CustomerField) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = "id";
            $obj->ORDER_BY_FIELDS = "customer_id, c_system_id";

            $obj->UNIQUE_KEY = ["customer_id", "c_system_id"];

            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
        } else {
            // CustomerFieldArTranslator::initData();
            // CustomerFieldEnTranslator::initData();
        }
    }
    public static $DB_STRUCTURE = [
        "id" => [
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "TYPE" => "PK",
        ],
        "customer_id" => [
            "SHORTNAME" => "customer",
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => false,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "SIZE" => 32,
            "MANDATORY" => true,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "customer",
            "ANSMODULE" => "sms",
            "RELATION" => "OneToMany",
            "READONLY" => false,
        ],
        "c_system_id" => [
            "SHORTNAME" => "system",
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "c_system",
            "ANSMODULE" => "sms",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "field0_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field1_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field2_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field3_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "field4_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "YN",
            "READONLY" => false,
        ],
        "field5_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "YN",
            "READONLY" => false,
        ],
        "field6_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "YN",
            "READONLY" => false,
        ],
        "field7_value" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 255,
            "UTF8" => true,
            "TYPE" => "YN",
            "READONLY" => false,
        ],
        "creation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "creation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "update_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "update_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "validation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "validation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "active" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "DEFAULT" => "Y",
            "TYPE" => "YN",
        ],
        "version" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "INT",
        ],
        "update_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "delete_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "display_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "sci_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "scenario_item",
            "ANSMODULE" => "pag",
        ],
        "tech_notes" => [
            "TYPE" => "TEXT",
            "CATEGORY" => "FORMULA",
            "SHOW-ADMIN" => true,
            "STEP" => "all",
            "TOKEN_SEP" => "§",
            "READONLY" => true,
            "NO-ERROR-CHECK" => true,
        ],
    ];
}

