<?php
class MsgSenderConfigAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof SenderConfig) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = "sender_config_name";
            $obj->ORDER_BY_FIELDS = "sender_config_code";
            $obj->OBJECT_CODE = 'sender_config_code';
            $obj->AUDIT_DATA = true;
            $obj->UNIQUE_KEY = array('sender_config_code');

            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
        } else {
            // SenderConfigArTranslator::initData();
            // SenderConfigEnTranslator::initData();
        }
    }
    public static $DB_STRUCTURE = [
        "id" => [
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "TYPE" => "PK",
        ],
        "sender_config_code" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 16,
            "MIN-SIZE" => 3,
            "CHAR_TEMPLATE" => "ALPHABETIC,NUMERIC,UNDERSCORE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "sender_config_name" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "MIN-SIZE" => 5,
            "CHAR_TEMPLATE" => "ARABIC-CHARS,SPACE",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "sender_config_desc" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => "AREA",
            "MANDATORY" => true,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "c_system_id" => [
            "SHORTNAME" => "system",
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "FK",
            "ANSWER" => "c_system",
            "ANSMODULE" => "msg",
            "RELATION" => "ManyToOne",
            "READONLY" => false,
        ],
        "module_code" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 16,
            "MIN-SIZE" => 3,
            "CHAR_TEMPLATE" => "ALPHABETIC,NUMERIC,UNDERSCORE",
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "subject" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 128,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
            "AUDIT" => 3,
        ],
        "body" => [
            "SEARCH" => false,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => "AREA",
            "UTF8" => true,
            "ROWS" => 8,
            "FORMAT" => "PRE",
            "TYPE" => "TEXT",
            "READONLY" => false,
            "AUDIT" => 3,
        ],
        "frequency" => [
            "SEARCH" => true,
            "QSEARCH" => true,
            "SHOW" => true,
            "RETRIEVE" => true,
            "EDIT" => true,
            "QEDIT" => true,
            "SIZE" => 32,
            "UTF8" => false,
            "TYPE" => "ENUM",
            "ANSWER" => "FUNCTION",
            "ANSMODULE" => "scd",
            "READONLY" => false,
            "AUDIT" => 3,
        ],
        "exec_params" => [
            "SEARCH" => false,
            "QSEARCH" => false,
            "SHOW" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "QEDIT" => false,
            "SIZE" => 128,
            "UTF8" => true,
            "TYPE" => "TEXT",
            "READONLY" => false,
        ],
        "customer_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => false,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "all_message_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => false,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "sms_sent_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => true,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "last_sms_sent_date" => [
            "TYPE" => "DATE",
            "FORMAT" => "HIJRI_UNIT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => true,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "sms_wait_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => true,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "email_sent_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => false,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "email_wait_count" => [
            "TYPE" => "INT",
            "CATEGORY" => "FORMULA",
            "SHOW" => true,
            "EDIT" => true,
            "READONLY" => true,
            "RETRIEVE" => false,
            // "LINK-URL" => "#",
            // "LINK-CSS" => "nice_link",
        ],
        "creation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "creation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "update_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
        ],
        "update_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "validation_user_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => true,
            "TYPE" => "FK",
            "ANSWER" => "auser",
            "ANSMODULE" => "ums",
            "WHERE" =>
                "id in (select id_auser from c0ums.module_auser where id_module = 1267)",
        ],
        "validation_date" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "DATETIME",
        ],
        "active" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "QEDIT" => false,
            "DEFAULT" => "Y",
            "TYPE" => "YN",
        ],
        "version" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "INT",
        ],
        "update_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "delete_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "display_groups_mfk" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "ANSWER" => "ugroup",
            "ANSMODULE" => "ums",
            "TYPE" => "MFK",
        ],
        "sci_id" => [
            "SHOW-ADMIN" => true,
            "RETRIEVE" => false,
            "EDIT" => false,
            "TYPE" => "FK",
            "ANSWER" => "scenario_item",
            "ANSMODULE" => "pag",
        ],
        "tech_notes" => [
            "TYPE" => "TEXT",
            "CATEGORY" => "FORMULA",
            "SHOW-ADMIN" => true,
            "STEP" => "all",
            "TOKEN_SEP" => "§",
            "READONLY" => true,
            "NO-ERROR-CHECK" => true,
        ],
    ];
}
